Repository Endava/BEEQ, pull requests merged in 2023-07, with the labels that each got.

#316 fix(notification): notification rendered as visible with `open="false"`
  packages/bee-q/src/components.d.ts
  packages/bee-q/src/components/notification/__tests__/bq-notification.e2e.ts
  packages/bee-q/src/components/notification/_storybook/bq-notification.stories.tsx
  packages/bee-q/src/components/notification/bq-notification.tsx
  packages/bee-q/src/components/notification/readme.md
  packages/bee-q/src/components/notification/scss/bq-notification.scss
Labels: bug 🐛

#358 revert(deps): update dependency prettier to v3
  .github/renovate.json5
  package-lock.json
  package.json
  packages/bee-q/src/global/styles/mixins/_keyframes.scss
  packages/bee-q/src/shared/test-utils/__tests__/computedStyle.spec.ts
  packages/bee-q/src/shared/test-utils/computedStyle.ts
Labels: bug 🐛, chore ⚙️

#344 feat(input): add new `<bq-input>` component
  package-lock.json
  packages/bee-q/.storybook/preview.ts
  packages/bee-q/src/components.d.ts
  packages/bee-q/src/components/button/readme.md
  packages/bee-q/src/components/icon/readme.md
  packages/bee-q/src/components/input/__tests__/bq-input.e2e.ts
  packages/bee-q/src/components/input/_storybook/bq-input.mdx
  packages/bee-q/src/components/input/_storybook/bq-input.stories.tsx
  packages/bee-q/src/components/input/bq-input.tsx
  packages/bee-q/src/components/input/bq-input.types.ts
  packages/bee-q/src/components/input/readme.md
  packages/bee-q/src/components/input/scss/bq-input.scss
  packages/bee-q/src/components/input/scss/bq-input.variables.scss
  packages/bee-q/src/components/tooltip/bq-tooltip.tsx
  packages/bee-q/src/tools/angular-value-accessor-config.ts
Labels: feature 🛠

#371 fix(input): focus style missing on consumer apps
  packages/bee-q/src/components/input/bq-input.tsx
  packages/bee-q/src/components/input/scss/bq-input.scss
  tailwind.config.ts
Labels: bug 🐛

#388 feat(Typography): add global typography CSS styles
  packages/bee-q/.storybook/main.ts
  packages/bee-q/src/_storybook/.gitkeep
  packages/bee-q/src/_storybook/foundation/typography.mdx
  packages/bee-q/src/components/badge/bq-badge.tsx
  packages/bee-q/src/components/breadcrumb-item/scss/bq-breadcrumb-item.variables.scss
  packages/bee-q/src/components/button/scss/bq-button.scss
  packages/bee-q/src/components/checkbox/bq-checkbox.tsx
  packages/bee-q/src/components/notification/bq-notification.tsx
  packages/bee-q/src/components/radio/scss/bq-radio.scss
  packages/bee-q/src/components/spinner/bq-spinner.tsx
  packages/bee-q/src/components/status/bq-status.tsx
  packages/bee-q/src/components/switch/scss/bq-switch.scss
  packages/bee-q/src/components/tab/scss/bq-tab-variables.scss
  packages/bee-q/src/components/tooltip/scss/bq-tooltip.variables.scss
  packages/bee-q/src/global/styles/default.scss
  packages/bee-q/src/global/styles/tailwind.pcss
  packages/bee-q/src/global/styles/utils/_typography.scss
  packages/bee-q/src/global/styles/utils/index.scss
  packages/bee-q/src/global/styles/variables/_typography.scss
  tailwind.config.ts
Labels: feature 🛠

#402 fix(tab): update active tab when value is changed externally
  packages/bee-q/src/components/tab-group/__tests__/bq-tab-group.e2e.ts
  packages/bee-q/src/components/tab-group/bq-tab-group.tsx
Labels: bug 🐛

#253 feature(option): add new `<bq-option>` component.
  packages/bee-q/src/components.d.ts
  packages/bee-q/src/components/option-group/__tests__/bq-option-group.e2e.ts
  packages/bee-q/src/components/option-group/bq-option-group.tsx
  packages/bee-q/src/components/option-group/readme.md
  packages/bee-q/src/components/option-group/scss/bq-option-group-variables.scss
  packages/bee-q/src/components/option-group/scss/bq-option-group.scss
  packages/bee-q/src/components/option-list/__tests__/bq-option-list.e2e.ts
  packages/bee-q/src/components/option-list/bq-option-list.tsx
  packages/bee-q/src/components/option-list/readme.md
  packages/bee-q/src/components/option-list/scss/bq-option-list.scss
  packages/bee-q/src/components/option-list/scss/bq-option-list.variables.scss
  packages/bee-q/src/components/option/__tests__/bq-option.e2e.ts
  packages/bee-q/src/components/option/_storybook/bq-option.mdx
  packages/bee-q/src/components/option/_storybook/bq-option.stories.tsx
  packages/bee-q/src/components/option/bq-option.tsx
  packages/bee-q/src/components/option/readme.md
  packages/bee-q/src/components/option/scss/bq-option-variables.scss
  packages/bee-q/src/components/option/scss/bq-option.scss
Labels: feature 🛠
