Repository Endava/BEEQ, pull requests merged in 2023-08, with the labels that each got.

#393 feat(textarea): add new `bq-textarea` component
  packages/bee-q/project.json
  packages/bee-q/src/components.d.ts
  packages/bee-q/src/components/input/scss/bq-input.variables.scss
  packages/bee-q/src/components/textarea/__tests__/bq-textarea.e2e.ts
  packages/bee-q/src/components/textarea/_storybook/bq-textarea.mdx
  packages/bee-q/src/components/textarea/_storybook/bq-textarea.stories.tsx
  packages/bee-q/src/components/textarea/bq-textarea.tsx
  packages/bee-q/src/components/textarea/bq-textarea.types.ts
  packages/bee-q/src/components/textarea/readme.md
  packages/bee-q/src/components/textarea/scss/bq-textarea.scss
  packages/bee-q/src/components/textarea/scss/bq-textarea.variables.scss
Labels: feature 🛠

#406 chore(Nx): update to Nx 16
  .circleci/config.yml
  .github/workflows/publish.yml
  commitlint.config.js
  nx.json
  package-lock.json
  package.json
  packages/bee-q-angular/project.json
  packages/bee-q-icons/.babelrc
  packages/bee-q-icons/project.json
  packages/bee-q-react/project.json
  packages/bee-q-react/tsconfig.json
  packages/bee-q-react/tsconfig.lib.json
  packages/bee-q/project.json
  project.json
  tsconfig.base.json
  workspace.json
Labels: chore ⚙️

#412 ci(CircleCI): use parallelism for faster tests
  .circleci/config.yml
  .github/renovate.json5
Labels: chore ⚙️

#414 refactor(sleep): replace promise implementation with nodejs timers
  packages/bee-q/src/shared/test-utils/sleep.ts
Labels: refactor 🧑🏼‍🔧

#428 fix(Avatar): trim initials text only if exist
  packages/bee-q/src/_storybook/foundation/typography.mdx
  packages/bee-q/src/components/avatar/bq-avatar.tsx
Labels: bug 🐛

#246 feature(Dropdown): add new `bq-panel` and `bq-dropdown` components
  packages/bee-q/src/components.d.ts
  packages/bee-q/src/components/dropdown/__tests__/bq-dropdown.e2e.ts
  packages/bee-q/src/components/dropdown/_storybook/bq-dropdown.mdx
  packages/bee-q/src/components/dropdown/_storybook/bq-dropdown.stories.tsx
  packages/bee-q/src/components/dropdown/bq-dropdown.tsx
  packages/bee-q/src/components/dropdown/readme.md
  packages/bee-q/src/components/dropdown/scss/bq-dropdown.scss
  packages/bee-q/src/components/option-list/__tests__/bq-option-list.e2e.ts
  packages/bee-q/src/components/panel/__tests__/bq-panel.e2e.ts
  packages/bee-q/src/components/panel/bq-panel.tsx
  packages/bee-q/src/components/panel/readme.md
  packages/bee-q/src/components/panel/scss/bq-panel-variables.scss
  packages/bee-q/src/components/panel/scss/bq-panel.scss
  packages/bee-q/src/services/libraries/floating-ui/index.ts
Labels: feature 🛠

#436 chore(Sonarcloud): update code duplications exclusion pattern
  sonar-project.properties
Labels: chore ⚙️

#437 fix(FloatingUI): use object spread instead of `Object.assign()`
  packages/bee-q/src/services/libraries/floating-ui/index.ts
  sonar-project.properties
Labels: bug 🐛

#435 feat(Theme): add dark mode support
  config/tailwind.declarative.colors.ts
  config/tailwind.primitve.colors.ts
  config/theme/default/dark.ts
  config/theme/default/index.ts
  config/theme/default/light.ts
  config/theme/default/root.ts
  package-lock.json
  package.json
  packages/bee-q/.storybook/preview.ts
  packages/bee-q/src/_storybook/foundation/typography.mdx
  packages/bee-q/src/components/avatar/scss/bq-avatar.variables.scss
  packages/bee-q/src/components/badge/scss/bq-badge.variables.scss
  packages/bee-q/src/components/breadcrumb-item/scss/bq-breadcrumb-item.scss
  packages/bee-q/src/components/breadcrumb-item/scss/bq-breadcrumb-item.variables.scss
  packages/bee-q/src/components/button/scss/bq-button.scss
  packages/bee-q/src/components/checkbox/bq-checkbox.tsx
  packages/bee-q/src/components/checkbox/scss/bq-checkbox.scss
  packages/bee-q/src/components/dialog/_storybook/bq-dialog.stories.tsx
  packages/bee-q/src/components/dialog/bq-dialog.tsx
  packages/bee-q/src/components/dialog/scss/bq-dialog.scss
  packages/bee-q/src/components/dialog/scss/bq-dialog.variables.scss
  packages/bee-q/src/components/dropdown/_storybook/bq-dropdown.stories.tsx
  packages/bee-q/src/components/input/scss/bq-input.scss
  packages/bee-q/src/components/input/scss/bq-input.variables.scss
  packages/bee-q/src/components/option/scss/bq-option.scss
  packages/bee-q/src/components/radio/scss/bq-radio.scss
  packages/bee-q/src/components/side-menu-item/scss/bq-side-menu-item.variables.scss
  packages/bee-q/src/components/side-menu/_storybook/bq-side-menu.stories.tsx
  packages/bee-q/src/components/side-menu/scss/bq-side-menu.scss
  packages/bee-q/src/components/side-menu/scss/bq-side-menu.variables.scss
  packages/bee-q/src/components/switch/bq-switch.tsx
  packages/bee-q/src/components/tab/bq-tab.tsx
  packages/bee-q/src/components/textarea/scss/bq-textarea.variables.scss
  packages/bee-q/src/global/styles/default.scss
  packages/bee-q/src/global/styles/tailwind.pcss
  packages/bee-q/src/global/styles/themes/default/_bg-colors.scss
  packages/bee-q/src/global/styles/themes/default/_icon-colors.scss
  packages/bee-q/src/global/styles/themes/default/_spacing.scss
  packages/bee-q/src/global/styles/themes/default/_stroke-colors.scss
  packages/bee-q/src/global/styles/themes/default/_text-colors.scss
  packages/bee-q/src/global/styles/themes/default/_ui-colors.scss
  packages/bee-q/src/global/styles/themes/default/index.scss
  packages/bee-q/src/global/styles/utils/_typography.scss
  packages/bee-q/src/global/styles/variables/_base.scss
  packages/bee-q/src/global/styles/variables/_border-radius.scss
  packages/bee-q/src/global/styles/variables/_box-shadow.scss
  packages/bee-q/src/global/styles/variables/_colors.scss
  packages/bee-q/src/global/styles/variables/_typography.scss
  packages/bee-q/src/global/styles/variables/index.scss
  packages/bee-q/stencil.config.ts
  postcss.config.js
  tailwind.config.ts
Labels: feature 🛠

#415 refactor(debounce): replace setTimeout with requestAnimationFrame
  packages/bee-q/src/shared/utils/__tests__/debounce.spec.ts
  packages/bee-q/src/shared/utils/__tests__/setRafTimeout.spec.ts
  packages/bee-q/src/shared/utils/debounce.ts
  packages/bee-q/src/shared/utils/index.ts
  packages/bee-q/src/shared/utils/setRafTimeout.ts
Labels: refactor 🧑🏼‍🔧

#453 fix(side menu item): misalignment when menu is collapsed
  packages/bee-q/src/components/side-menu-item/__tests__/bq-side-menu-item.e2e.ts
  packages/bee-q/src/components/side-menu-item/bq-side-menu-item.tsx
  packages/bee-q/src/components/side-menu-item/scss/bq-side-menu-item.scss
  packages/bee-q/src/components/tooltip/bq-tooltip.tsx
Labels: bug 🐛

#462 fix(beeq-react): package json npm package has wrong paths
  package.json
  packages/beeq-react/package.json
  packages/beeq/project.json
Labels: bug 🐛

#463 chore(BEEQ react): build using TypeScript instead of Rollup
  package.json
  packages/beeq-angular/package.json
  packages/beeq-react/package.json
  packages/beeq-react/project.json
  packages/beeq-react/tsconfig.json
  packages/beeq-react/tsconfig.lib.json
  packages/beeq/package.json
Labels: chore ⚙️

#474 style(CSS): set HTML font base to 1rem
  packages/beeq/.storybook/preview.ts
  packages/beeq/src/_storybook/foundation/typography.mdx
  packages/beeq/src/components/avatar/_storybook/bq-avatar.stories.tsx
  packages/beeq/src/components/badge/_storybook/bq-badge.stories.tsx
  packages/beeq/src/global/styles/variables/_base.scss
Labels: chore ⚙️

#501 docs(Storybook): improve styles and BEEQ light/dark mode
  .gitignore
  packages/beeq/.storybook/assets/css/font.css
  packages/beeq/.storybook/assets/css/preview.css
  packages/beeq/.storybook/assets/css/storybook.css
  packages/beeq/.storybook/main.ts
  packages/beeq/.storybook/manager.ts
  packages/beeq/.storybook/preview-head.html
  packages/beeq/.storybook/preview.ts
  packages/beeq/project.json
  packages/beeq/src/_storybook/foundation/typography.mdx
  packages/beeq/src/_storybook/foundation/typography.stories.mdx
  packages/beeq/src/components.d.ts
  packages/beeq/src/components/avatar/_storybook/bq-avatar.mdx
  packages/beeq/src/components/avatar/bq-avatar.tsx
  packages/beeq/src/components/avatar/readme.md
  packages/beeq/src/components/badge/_storybook/bq-badge.mdx
  packages/beeq/src/components/breadcrumb/_storybook/bq-breadcrumb.mdx
  packages/beeq/src/components/button/_storybook/bq-button.mdx
  packages/beeq/src/components/checkbox/_storybook/bq-checkbox.mdx
  packages/beeq/src/components/dialog/_storybook/bq-dialog.mdx
  packages/beeq/src/components/divider/_storybook/bq-divider.mdx
  packages/beeq/src/components/dropdown/_storybook/bq-dropdown.mdx
  packages/beeq/src/components/icon/_storybook/bq-icon.mdx
  packages/beeq/src/components/input/_storybook/bq-input.mdx
  packages/beeq/src/components/notification/_storybook/bq-notification.mdx
  packages/beeq/src/components/option-list/bq-option-list.tsx
  packages/beeq/src/components/option-list/readme.md
  packages/beeq/src/components/option/_storybook/bq-option.mdx
  packages/beeq/src/components/radio-group/_storybook/bq-radio-group.mdx
  packages/beeq/src/components/select/_storybook/bq-select.mdx
  packages/beeq/src/components/side-menu-item/_storybook/bq-side-menu-item.mdx
  packages/beeq/src/components/side-menu/_storybook/bq-side-menu.mdx
  packages/beeq/src/components/slider/_storybook/bq-slider.mdx
  packages/beeq/src/components/spinner/_storybook/bq-spinner.mdx
  packages/beeq/src/components/status/_storybook/bq-status.mdx
  packages/beeq/src/components/switch/_storybook/bq-switch.mdx
  packages/beeq/src/components/tab-group/_storybook/bq-tab-group.mdx
  packages/beeq/src/components/tab/_storybook/bq-tab.mdx
  packages/beeq/src/components/textarea/_storybook/bq-textarea.mdx
  packages/beeq/src/components/toast/_storybook/bq-toast.mdx
  packages/beeq/src/components/tooltip/_storybook/bq-tooltip.mdx
  tools/generators/plop/scss-variables.hbs
  tools/generators/plop/storybook-docs.hbs
Labels: documentation 📚
