Repository Endava/BEEQ, pull requests merged in 2023-12, with the labels that each got.

#694 feat(Empty State): add new bq-empty-state component
  packages/beeq/src/components.d.ts
  packages/beeq/src/components/empty-state/__tests__/bq-empty-state.e2e.ts
  packages/beeq/src/components/empty-state/_storybook/bq-empty-state.mdx
  packages/beeq/src/components/empty-state/_storybook/bq-empty-state.stories.tsx
  packages/beeq/src/components/empty-state/bq-empty-state.tsx
  packages/beeq/src/components/empty-state/bq-empty-state.types.ts
  packages/beeq/src/components/empty-state/readme.md
  packages/beeq/src/components/empty-state/scss/bq-empty-state.scss
  packages/beeq/src/components/icon/readme.md
Labels: feature 🛠

#697 feat(Accordion): add new `bq-accordion` and `bq-accordion-group` components
  package-lock.json
  packages/beeq/project.json
  packages/beeq/src/components.d.ts
  packages/beeq/src/components/accordion-group/__tests__/bq-accordion-group.e2e.ts
  packages/beeq/src/components/accordion-group/_storybook/bq-accordion-group.stories.tsx
  packages/beeq/src/components/accordion-group/bq-accordion-group.tsx
  packages/beeq/src/components/accordion-group/readme.md
  packages/beeq/src/components/accordion-group/scss/bq-accordion-group.scss
  packages/beeq/src/components/accordion-group/scss/bq-accordion-group.variables.scss
  packages/beeq/src/components/accordion/__tests__/bq-accordion.e2e.ts
  packages/beeq/src/components/accordion/_storybook/bq-accordion.mdx
  packages/beeq/src/components/accordion/_storybook/bq-accordion.stories.tsx
  packages/beeq/src/components/accordion/bq-accordion.tsx
  packages/beeq/src/components/accordion/bq-accordion.types.ts
  packages/beeq/src/components/accordion/helper/index.ts
  packages/beeq/src/components/accordion/readme.md
  packages/beeq/src/components/accordion/scss/bq-accordion.scss
  packages/beeq/src/components/accordion/scss/bq-accordion.variables.scss
  packages/beeq/src/components/icon/readme.md
Labels: feature 🛠

#708 fix(Textarea): export missing shadow DOM parts
  .lintstagedrc.mjs
  packages/beeq/src/components/textarea/bq-textarea.tsx
  packages/beeq/src/components/textarea/readme.md
Labels: bug 🐛

#715 chore(CI): add a Github pages deploy workflow
  .github/workflows/deploy.yml
Labels: chore ⚙️

#709 feat(Button): add `border` property to support border-radius changes
  .github/workflows/deploy.yml
  .github/workflows/publish.yml
  package-lock.json
  package.json
  packages/beeq-tailwindcss/package.json
  packages/beeq/src/components.d.ts
  packages/beeq/src/components/button/_storybook/bq-button.stories.tsx
  packages/beeq/src/components/button/bq-button.tsx
  packages/beeq/src/components/button/bq-button.types.ts
  packages/beeq/src/components/button/readme.md
  packages/beeq/src/components/button/scss/bq-button.scss
  packages/beeq/src/components/button/scss/bq-button.variables.scss
Labels: feature 🛠

#695 feat(Tag): add new `bq-tag` component
  packages/beeq/src/components.d.ts
  packages/beeq/src/components/button/readme.md
  packages/beeq/src/components/icon/readme.md
  packages/beeq/src/components/tag/__tests__/bq-tag.e2e.ts
  packages/beeq/src/components/tag/_storybook/bq-tag.mdx
  packages/beeq/src/components/tag/_storybook/bq-tag.stories.tsx
  packages/beeq/src/components/tag/bq-tag.tsx
  packages/beeq/src/components/tag/bq-tag.types.ts
  packages/beeq/src/components/tag/helper/index.ts
  packages/beeq/src/components/tag/readme.md
  packages/beeq/src/components/tag/scss/bq-tag.scss
  packages/beeq/src/components/tag/scss/bq-tag.variables.scss
Labels: feature 🛠
