Repository Endava/BEEQ, pull requests merged in 2023-11, with the labels that each got.

#629 fix(Badge): remove border styles
  package-lock.json
  packages/beeq/src/components/badge/__tests__/bq-badge.e2e.ts
  packages/beeq/src/components/badge/scss/bq-badge.variables.scss
Labels: refactor 🧑🏼‍🔧

#673 chore(deps): update Angular to v17.0.3
  .github/renovate.json5
  CONTRIBUTING.md
  package-lock.json
  package.json
Labels: chore ⚙️, dependencies 📦

#675 feat(Alert): add new bq-alert component
  packages/beeq/src/components.d.ts
  packages/beeq/src/components/alert/__tests__/bq-alert.e2e.ts
  packages/beeq/src/components/alert/_storybook/bq-alert.mdx
  packages/beeq/src/components/alert/_storybook/bq-alert.stories.tsx
  packages/beeq/src/components/alert/bq-alert.tsx
  packages/beeq/src/components/alert/bq-alert.types.ts
  packages/beeq/src/components/alert/readme.md
  packages/beeq/src/components/alert/scss/bq-alert.scss
  packages/beeq/src/components/alert/scss/bq-alert.variables.scss
  packages/beeq/src/components/button/readme.md
  packages/beeq/src/components/icon/readme.md
Labels: feature 🛠
