Repository Endava/BEEQ, pull requests merged in 2023-09, with the labels that each got.

#502 fix(debounce): cancel is not a function
  packages/beeq/src/shared/utils/__tests__/debounce.spec.ts
  packages/beeq/src/shared/utils/debounce.ts
Labels: bug 🐛

#503 chore(ESLint): improve modules import
  .circleci/config.yml
  packages/beeq/.eslintrc.json
  packages/beeq/src/components/avatar/bq-avatar.tsx
  packages/beeq/src/components/badge/bq-badge.tsx
  packages/beeq/src/components/breadcrumb-item/bq-breadcrumb-item.tsx
  packages/beeq/src/components/breadcrumb/_storybook/bq-breadcrumb.stories.tsx
  packages/beeq/src/components/breadcrumb/bq-breadcrumb.tsx
  packages/beeq/src/components/checkbox/bq-checkbox.tsx
  packages/beeq/src/components/dialog/_storybook/bq-dialog.stories.tsx
  packages/beeq/src/components/divider/bq-divider.tsx
  packages/beeq/src/components/dropdown/_storybook/bq-dropdown.stories.tsx
  packages/beeq/src/components/dropdown/bq-dropdown.tsx
  packages/beeq/src/components/notification/_storybook/bq-notification.stories.tsx
  packages/beeq/src/components/option-group/bq-option-group.tsx
  packages/beeq/src/components/option-list/bq-option-list.tsx
  packages/beeq/src/components/option/bq-option.tsx
  packages/beeq/src/components/panel/bq-panel.tsx
  packages/beeq/src/components/radio-group/bq-radio-group.tsx
  packages/beeq/src/components/radio/bq-radio.tsx
  packages/beeq/src/components/slider/bq-slider.tsx
  packages/beeq/src/components/spinner/bq-spinner.tsx
  packages/beeq/src/components/status/bq-status.tsx
  packages/beeq/src/components/tab-group/bq-tab-group.tsx
  packages/beeq/src/components/textarea/_storybook/bq-textarea.stories.tsx
  packages/beeq/src/components/toast/bq-toast.tsx
Labels: chore ⚙️

#505 feat(Colors): add new `alt` and `alt-disabled` color tokens
  config/tailwind.declarative.colors.ts
  config/theme/default/dark.ts
  config/theme/default/light.ts
  packages/beeq/.storybook/assets/css/preview.css
  packages/beeq/src/components/button/scss/bq-button.scss
  packages/beeq/src/components/switch/bq-switch.tsx
  packages/beeq/src/components/switch/scss/bq-switch.scss
Labels: feature 🛠
