Repository Endava/BEEQ, pull requests merged in 2023-06, with the labels that each got.

#268 fix(tokens): make feedback text color tokens accessible
  packages/bee-q/src/global/styles/themes/default/_text-colors.scss
Labels: chore ⚙️, feature 🛠

#205 fix(tab group): make divider full width
  packages/bee-q/src/components.d.ts
  packages/bee-q/src/components/tab-group/__tests__/bq-tab-group.e2e.ts
  packages/bee-q/src/components/tab-group/_storybook/bq-tab-group.stories.tsx
  packages/bee-q/src/components/tab-group/bq-tab-group.tsx
  packages/bee-q/src/components/tab-group/readme.md
  packages/bee-q/src/components/tab-group/scss/bq-tab-group.scss
  packages/bee-q/src/components/tab/_storybook/bq-tab.stories.tsx
  packages/bee-q/src/components/tab/bq-tab.tsx
  packages/bee-q/src/components/tab/readme.md
  packages/bee-q/src/components/tab/scss/bq-tab.scss
  packages/bee-q/src/global/styles/mixins/_scrollbar.scss
  packages/bee-q/src/global/styles/mixins/index.scss
  packages/bee-q/stencil.config.ts
Labels: bug 🐛

#281 feat(chore): remove tailwind line-clamp plugin
  package-lock.json
  package.json
  tailwind.config.ts
Labels: chore ⚙️

#280 fix(chore): plopjs storybook eslint import order
  tools/generators/plop/scss-variables.hbs
  tools/generators/plop/storybook.hbs
Labels: bug 🐛

#287 feat(CSS reset): improve custom CSS reset
  packages/bee-q/src/global/styles/tailwind.pcss
Labels: feature 🛠

#289 feat(side menu): new `<bq-side-menu>` and `<bq-side-menu-item>` components
  packages/bee-q/src/components.d.ts
  packages/bee-q/src/components/side-menu-item/__tests__/bq-side-menu-item.e2e.ts
  packages/bee-q/src/components/side-menu-item/_storybook/bq-side-menu-item.mdx
  packages/bee-q/src/components/side-menu-item/_storybook/bq-side-menu-item.stories.tsx
  packages/bee-q/src/components/side-menu-item/bq-side-menu-item.tsx
  packages/bee-q/src/components/side-menu-item/readme.md
  packages/bee-q/src/components/side-menu-item/scss/bq-side-menu-item.scss
  packages/bee-q/src/components/side-menu-item/scss/bq-side-menu-item.variables.scss
  packages/bee-q/src/components/side-menu/__tests__/bq-side-menu.e2e.ts
  packages/bee-q/src/components/side-menu/_storybook/bq-side-menu.mdx
  packages/bee-q/src/components/side-menu/_storybook/bq-side-menu.stories.tsx
  packages/bee-q/src/components/side-menu/bq-side-menu.tsx
  packages/bee-q/src/components/side-menu/bq-side-menu.types.ts
  packages/bee-q/src/components/side-menu/readme.md
  packages/bee-q/src/components/side-menu/scss/bq-side-menu.scss
  packages/bee-q/src/components/side-menu/scss/bq-side-menu.variables.scss
  packages/bee-q/src/components/tooltip/readme.md
  packages/bee-q/src/components/tooltip/scss/bq-tooltip.scss
  packages/bee-q/src/global/styles/_components.scss
  packages/bee-q/src/global/styles/default.scss
  packages/bee-q/src/global/styles/utils/_utility.scss
  sonar-project.properties
  tailwind.config.ts
Labels: feature 🛠

#291 fix(angular wrapper): peerDependencies and versions allowed
  package-lock.json
  package.json
  packages/bee-q-angular/package.json
  packages/bee-q/package.json
Labels: bug 🐛

#292 fix(react wrapper): peerDependencies version allowed
  package-lock.json
  packages/bee-q-react/package.json
Labels: chore ⚙️

#269 feat(dialog): add new `<bq-dialog>` component
  config/tailwind.primitve.colors.ts
  packages/bee-q/src/components.d.ts
  packages/bee-q/src/components/button/readme.md
  packages/bee-q/src/components/dialog/__tests__/bq-dialog.e2e.ts
  packages/bee-q/src/components/dialog/_storybook/bq-dialog.mdx
  packages/bee-q/src/components/dialog/_storybook/bq-dialog.stories.tsx
  packages/bee-q/src/components/dialog/bq-dialog.tsx
  packages/bee-q/src/components/dialog/bq-dialog.types.ts
  packages/bee-q/src/components/dialog/readme.md
  packages/bee-q/src/components/dialog/scss/bq-dialog.scss
  packages/bee-q/src/components/dialog/scss/bq-dialog.variables.scss
  packages/bee-q/src/components/icon/readme.md
  packages/bee-q/src/global/styles/themes/default/_bg-colors.scss
  packages/bee-q/src/global/styles/variables/_colors.scss
Labels: feature 🛠

#305 fix(dialog): footer padding when standard and highlight
  packages/bee-q/src/components/dialog/bq-dialog.tsx
  packages/bee-q/src/components/dialog/scss/bq-dialog.scss
  packages/bee-q/src/components/dialog/scss/bq-dialog.variables.scss
Labels: bug 🐛

#306 feat(dialog): allow disable backdrop overlay and `bqAfterOpen` event
  .github/workflows/publish.yml
  packages/bee-q/project.json
  packages/bee-q/src/components.d.ts
  packages/bee-q/src/components/dialog/_storybook/bq-dialog.stories.tsx
  packages/bee-q/src/components/dialog/bq-dialog.tsx
  packages/bee-q/src/components/dialog/readme.md
  packages/bee-q/src/components/dialog/scss/bq-dialog.scss
  packages/bee-q/src/components/dialog/scss/bq-dialog.variables.scss
Labels: feature 🛠

#307 fix(badge): not being full rounded with one digit
  .stylelintrc.json
  packages/bee-q/src/components/badge/bq-badge.tsx
  packages/bee-q/src/components/badge/scss/bq-badge.scss
  packages/bee-q/src/components/badge/scss/bq-badge.variables.scss
Labels: bug 🐛

#301 feat(toast): add toast component
  packages/bee-q/src/components.d.ts
  packages/bee-q/src/components/icon/readme.md
  packages/bee-q/src/components/toast/__tests__/bq-toast.e2e.ts
  packages/bee-q/src/components/toast/_storybook/bq-toast.mdx
  packages/bee-q/src/components/toast/_storybook/bq-toast.stories.tsx
  packages/bee-q/src/components/toast/bq-toast.tsx
  packages/bee-q/src/components/toast/bq-toast.types.ts
  packages/bee-q/src/components/toast/readme.md
  packages/bee-q/src/components/toast/scss/bq-toast.scss
  packages/bee-q/src/components/toast/scss/bq-toast.variables.scss
  packages/bee-q/src/global/styles/utils/_utility.scss
  tailwind.config.ts
Labels: feature 🛠

#267 feature(avatar): add badge
  packages/bee-q/src/components.d.ts
  packages/bee-q/src/components/avatar/__tests__/bq-avatar.e2e.ts
  packages/bee-q/src/components/avatar/_storybook/bq-avatar.stories.tsx
  packages/bee-q/src/components/avatar/bq-avatar.tsx
  packages/bee-q/src/components/avatar/scss/bq-avatar.scss
  packages/bee-q/src/components/avatar/scss/bq-avatar.variables.scss
  packages/bee-q/src/components/badge/bq-badge.tsx
  packages/bee-q/src/components/badge/readme.md
Labels: feature 🛠
