Repository Endava/BEEQ, pull requests merged in 2024-12, with the labels that each got.

#1353 feat(Radio): enable support for form-associated
  packages/beeq/src/components.d.ts
  packages/beeq/src/components/radio-group/_storybook/bq-radio-group.stories.tsx
  packages/beeq/src/components/radio-group/bq-radio-group.tsx
  packages/beeq/src/components/radio-group/readme.md
  packages/beeq/src/components/radio/bq-radio.tsx
  packages/beeq/src/components/radio/readme.md
  packages/beeq/src/components/radio/scss/bq-radio.scss
Labels: feature 🛠

#1362 feat(Date picker): enable support for form-associated
  packages/beeq/src/components/date-picker/_storybook/bq-date-picker.stories.tsx
  packages/beeq/src/components/date-picker/bq-date-picker.tsx
  packages/beeq/src/components/input/bq-input.tsx
Labels: feature 🛠

#1369 feat(Slider): enable support for form-associated
  packages/beeq/src/components.d.ts
  packages/beeq/src/components/slider/_storybook/bq-slider.stories.tsx
  packages/beeq/src/components/slider/bq-slider.tsx
  packages/beeq/src/components/slider/readme.md
  packages/beeq/src/components/switch/bq-switch.tsx
Labels: feature 🛠

#1370 feat(Textarea): enable support for form-associated
  packages/beeq/src/components.d.ts
  packages/beeq/src/components/textarea/__tests__/bq-textarea.e2e.ts
  packages/beeq/src/components/textarea/_storybook/bq-textarea.stories.tsx
  packages/beeq/src/components/textarea/bq-textarea.tsx
  packages/beeq/src/components/textarea/readme.md
  packages/beeq/src/components/textarea/scss/bq-textarea.variables.scss
Labels: feature 🛠

#1371 fix(Input): better `required` handler on form submit when value is empty
  packages/beeq/src/components.d.ts
  packages/beeq/src/components/input/_storybook/bq-input.stories.tsx
  packages/beeq/src/components/input/bq-input.tsx
  packages/beeq/src/components/input/readme.md
Labels: bug 🐛

#1382 chore(Nx): configure `nx release` and remove additional Nx plugins
  .github/workflows/publish.yml
  CHANGELOG.md
  nx.json
  package-lock.json
  package.json
  packages/beeq-angular/project.json
  packages/beeq-react/project.json
  packages/beeq-tailwindcss/project.json
  packages/beeq-vue/project.json
  packages/beeq/project.json
  project.json
Labels: chore ⚙️
