Repository Endava/BEEQ, pull requests merged in 2024-04, with the labels that each got.

#967 feat(Progress): add style and animation for indeterminate status
  packages/beeq/src/components/progress/__tests__/bq-progress.e2e.ts
  packages/beeq/src/components/progress/_storybook/bq-progress.stories.tsx
  packages/beeq/src/components/progress/bq-progress.tsx
  packages/beeq/src/components/progress/readme.md
  packages/beeq/src/components/progress/scss/bq-progress.scss
  packages/beeq/src/components/progress/scss/bq-progress.variables.scss
Labels: feature 🛠

#979 fix(Dialog): dialog closes on Esc down if `disable-close-esc-keydown` is enabled
  packages/beeq/src/components/dialog/bq-dialog.tsx
Labels: bug 🐛

#996 fix(Slider): unable to set or drag the Slider down to `0` value
  packages/beeq/src/components.d.ts
  packages/beeq/src/components/slider/__test__/bq-slider.e2e.ts
  packages/beeq/src/components/slider/__tests__/bq-slider.e2e.ts
  packages/beeq/src/components/slider/_storybook/bq-slider.stories.tsx
  packages/beeq/src/components/slider/bq-slider.tsx
  packages/beeq/src/components/slider/bq-slider.types.ts
  packages/beeq/src/components/slider/readme.md
  packages/beeq/src/components/slider/scss/bq-slider.scss
  packages/beeq/src/components/slider/scss/bq-slider.variables.scss
Labels: bug 🐛

#998 chore(Renovate): configure renovate to group all NPM dependencies
  .commitlintrc.ts
  .github/renovate.json5
  packages/beeq/project.json
Labels: chore ⚙️

#1004 fix(Slider): range type not rendering correctly when max value is greater than 10
  packages/beeq/src/components/slider/__tests__/bq-slider.e2e.ts
  packages/beeq/src/components/slider/_storybook/bq-slider.stories.tsx
  packages/beeq/src/components/slider/bq-slider.tsx
Labels: bug 🐛

#1011 refactor(Side menu): set background color to UI primary for the default variant
  .stylelintrc.json
  packages/beeq-tailwindcss/src/theme/colors/declarative.ts
  packages/beeq-tailwindcss/src/theme/default/dark.ts
  packages/beeq-tailwindcss/src/theme/default/light.ts
  packages/beeq-tailwindcss/src/theme/endava/dark.ts
  packages/beeq-tailwindcss/src/theme/endava/light.ts
  packages/beeq/src/components/side-menu-item/scss/bq-side-menu-item.variables.scss
  packages/beeq/src/components/side-menu/scss/bq-side-menu.scss
  packages/beeq/src/components/side-menu/scss/bq-side-menu.variables.scss
Labels: refactor 🧑🏼‍🔧

#1014 fix(Side Menu): menu items tooltip not showing correctly when collapsed
  packages/beeq/src/components/progress/bq-progress.tsx
  packages/beeq/src/components/slider/bq-slider.tsx
  packages/beeq/src/components/tooltip/bq-tooltip.tsx
  packages/beeq/src/components/tooltip/scss/bq-tooltip.scss
Labels: bug 🐛

#1017 fix(Select): initial value is not displayed when the component load
  packages/beeq/src/components/select/bq-select.tsx
Labels: bug 🐛

#1024 feat(Select): add support to search/filter the options list
  .github/renovate.json5
  packages/beeq/project.json
  packages/beeq/src/components.d.ts
  packages/beeq/src/components/option-list/bq-option-list.tsx
  packages/beeq/src/components/option/_storybook/bq-option.stories.tsx
  packages/beeq/src/components/option/bq-option.tsx
  packages/beeq/src/components/option/readme.md
  packages/beeq/src/components/option/scss/bq-option.scss
  packages/beeq/src/components/select/_storybook/bq-select.stories.tsx
  packages/beeq/src/components/select/bq-select.tsx
  packages/beeq/src/components/select/readme.md
  packages/beeq/src/components/select/scss/bq-select.scss
  packages/beeq/src/components/select/scss/bq-select.variables.scss
  packages/beeq/src/shared/utils/event.ts
  packages/beeq/src/shared/utils/index.ts
Labels: feature 🛠

#1025 feat(Select): add support for multiple selection
  package-lock.json
  packages/beeq/src/components.d.ts
  packages/beeq/src/components/select/_storybook/bq-select.stories.tsx
  packages/beeq/src/components/select/bq-select.tsx
  packages/beeq/src/components/select/readme.md
  packages/beeq/src/components/select/scss/bq-select.variables.scss
  packages/beeq/src/components/tag/__tests__/bq-tag.e2e.ts
  packages/beeq/src/components/tag/bq-tag.tsx
  packages/beeq/src/components/tag/helper/index.ts
  packages/beeq/src/components/tag/readme.md
  packages/beeq/src/components/tag/scss/bq-tag.variables.scss
Labels: feature 🛠

#1031 fix(Slider): lower value updated to max value
  packages/beeq/src/components/slider/bq-slider.tsx
Labels: bug 🐛

#1034 fix(Select): prevent bqClose to propagate further
  packages/beeq/src/components/select/bq-select.tsx
Labels: bug 🐛
