Repository Endava/BEEQ, pull requests merged in 2024-07, with the labels that each got.

#1153 docs(Storybook): add `Direction` toolbar action for content RTL/LTR
  package-lock.json
  package.json
  packages/beeq/.storybook/main.ts
  packages/beeq/.storybook/preview.ts
  patches/@storybook+core+8.2.4.patch
Labels: documentation 📚

#1130 refactor(Accordion): use CSS logical properties instead of physical values
  packages/beeq/src/components.d.ts
  packages/beeq/src/components/accordion-group/_storybook/bq-accordion-group.stories.tsx
  packages/beeq/src/components/accordion-group/bq-accordion-group.tsx
  packages/beeq/src/components/accordion-group/readme.md
  packages/beeq/src/components/accordion/_storybook/bq-accordion.stories.tsx
  packages/beeq/src/components/accordion/bq-accordion.tsx
  packages/beeq/src/components/accordion/helper/index.ts
  packages/beeq/src/components/accordion/readme.md
  packages/beeq/src/components/accordion/scss/bq-accordion.scss
Labels: refactor 🧑🏼‍🔧

#1154 chore(deps): update nx to v19.5.0
  package-lock.json
  package.json
Labels: chore ⚙️, dependencies 📦

#1155 fix(Drawer): open/close animation to be in sync with the content direction
  packages/beeq/src/components/drawer/_storybook/bq-drawer.stories.tsx
  packages/beeq/src/components/drawer/bq-drawer.tsx
Labels: bug 🐛

#1156 feat(Icon): add `--bq-icon--direction` and flip SVG automatically for `dir="rtl"`
  packages/beeq/src/components/icon/_storybook/bq-icon.stories.tsx
  packages/beeq/src/components/icon/scss/bq-icon.scss
  packages/beeq/src/global/styles/_components.scss
Labels: feature 🛠

#1106 refactor(Date Picker): use CSS logical properties instead of physical values
  packages/beeq/src/components/date-picker/_storybook/bq-date-picker.stories.tsx
  packages/beeq/src/components/date-picker/bq-date-picker.tsx
  packages/beeq/src/components/date-picker/scss/bq-date-picker.scss
Labels: refactor 🧑🏼‍🔧

#1157 refactor(Side menu): use CSS logical properties instead of physical values
  packages/beeq/src/components/side-menu/bq-side-menu.tsx
  packages/beeq/src/components/side-menu/scss/bq-side-menu.scss
  packages/beeq/src/global/styles/utils/_utility.scss
Labels: refactor 🧑🏼‍🔧

#1158 refactor(Steps): use CSS logical properties instead of physical values
  packages/beeq/src/components.d.ts
  packages/beeq/src/components/step-item/bq-step-item.tsx
  packages/beeq/src/components/step-item/readme.md
  packages/beeq/src/components/step-item/scss/bq-step-item.scss
  packages/beeq/src/components/steps/bq-steps.tsx
Labels: refactor 🧑🏼‍🔧

#1160 fix(Divider): default values to be in sync with Figma design
  packages/beeq/src/components/divider/__tests__/bq-divider.e2e.ts
  packages/beeq/src/components/divider/_storybook/bq-divider.stories.tsx
  packages/beeq/src/components/divider/bq-divider.tsx
  packages/beeq/src/components/divider/readme.md
  packages/beeq/src/components/divider/scss/bq-divider.scss
  packages/beeq/src/components/divider/scss/bq-divider.variables.scss
  packages/beeq/src/components/drawer/bq-drawer.tsx
  packages/beeq/src/components/steps/_storybook/bq-steps.stories.tsx
  packages/beeq/src/components/steps/bq-steps.tsx
  packages/beeq/src/components/steps/readme.md
Labels: bug 🐛

#1161 chore(renovate): improve automated dependency updates
  .github/renovate.json5
  package-lock.json
  package.json
Labels: chore ⚙️, dependencies 📦

#1172 fix(deps): missing `@stencil/core` dependency for framework targets
  .husky/branch-name.sh
  package-lock.json
  packages/beeq-angular/package.json
  packages/beeq-react/package.json
  packages/beeq-vue/package.json
  packages/beeq/.eslintrc.json
  packages/beeq/package.json
Labels: bug 🐛, chore ⚙️

#1173 docs(Storybook): add `Welcome` and `Foundation` sections as detached MDX stories
  packages/beeq/.storybook/main.ts
  packages/beeq/.storybook/preview.ts
  packages/beeq/src/_storybook/foundation/colors.mdx
  packages/beeq/src/_storybook/foundation/helper/index.ts
  packages/beeq/src/_storybook/foundation/typography.mdx
  packages/beeq/src/_storybook/foundation/typography.stories.mdx
  packages/beeq/src/_storybook/welcome.mdx
  packages/beeq/src/components/icon/_storybook/bq-icon.stories.tsx
  packages/beeq/src/global/assets/beeq-cover.svg
  packages/beeq/src/global/styles/utils/_utility.scss
Labels: documentation 📚

#1174 docs(Storybook): add Changelog page
  .gitignore
  nx.json
  packages/beeq/.storybook/assets/css/preview.css
  packages/beeq/.storybook/preview.ts
  packages/beeq/project.json
  packages/beeq/src/_storybook/changelog.mdx
Labels: documentation 📚
