Repository Endava/BEEQ, pull requests merged in 2024-05, with the labels that each got.

#1036 fix(Checkbox): bq-checkbox indeterminate property is wrongly typed
  packages/beeq/src/components.d.ts
  packages/beeq/src/components/checkbox/bq-checkbox.tsx
Labels: bug 🐛

#1037 fix(select): re-render tags when value change externally
  packages/beeq/src/components/select/__tests__/bq-select.e2e.ts
  packages/beeq/src/components/select/bq-select.tsx
Labels: bug 🐛

#1045 refactor(Icon): remove usage of `Env` from @stencil/core
  packages/beeq/src/components/icon/__tests__/bq-icon.e2e.ts
  packages/beeq/src/components/icon/bq-icon.tsx
  packages/beeq/src/components/icon/helper/request.ts
  packages/beeq/stencil.config.ts
Labels: refactor 🧑🏼‍🔧

#1051 fix(Slider): model is not reflecting value changes when using `ngModel` in Angular
  packages/beeq/src/components/slider/bq-slider.tsx
  packages/beeq/src/components/slider/bq-slider.types.ts
  packages/beeq/src/components/slider/readme.md
  packages/beeq/src/tools/angular-value-accessor-config.ts
Labels: bug 🐛

#1039 refactor(Button): change background color on hover for button link and text
  packages/beeq/src/components/button/scss/bq-button.scss
Labels: refactor 🧑🏼‍🔧

#1055 fix(Beeq Vue): remove `applyPolyfills()` function
  .circleci/config.yml
  packages/beeq-angular/package.json
  packages/beeq-react/package.json
  packages/beeq-vue/package.json
  packages/beeq-vue/src/plugin.ts
Labels: bug 🐛

#1057 refactor(Select): remove useless CSS rules
  packages/beeq/src/components/select/scss/bq-select.scss
  project.json
Labels: refactor 🧑🏼‍🔧

#1058 feat(button): add secondary button ghost variant
  packages/beeq/src/components/button/scss/bq-button.scss
Labels: bug 🐛

#1059 chore(Beeq): improve ESM exports and types export
  packages/beeq/package.json
  packages/beeq/src/index.ts
Labels: chore ⚙️

#1060 feat(Drawer): add support for custom footer divider
  packages/beeq/src/components/drawer/_storybook/bq-drawer.stories.tsx
  packages/beeq/src/components/drawer/bq-drawer.tsx
Labels: feature 🛠

#1029 feat(Date Picker): add new `bq-date-picker` component
  package-lock.json
  package.json
  packages/beeq/package.json
  packages/beeq/src/components.d.ts
  packages/beeq/src/components/button/readme.md
  packages/beeq/src/components/date-picker/__tests__/bq-date-picker.e2e.ts
  packages/beeq/src/components/date-picker/_storybook/bq-date-picker.mdx
  packages/beeq/src/components/date-picker/_storybook/bq-date-picker.stories.tsx
  packages/beeq/src/components/date-picker/bq-date-picker.tsx
  packages/beeq/src/components/date-picker/bq-date-picker.types.ts
  packages/beeq/src/components/date-picker/readme.md
  packages/beeq/src/components/date-picker/scss/bq-date-picker.scss
  packages/beeq/src/components/date-picker/scss/bq-date-picker.variables.scss
  packages/beeq/src/components/dropdown/readme.md
  packages/beeq/src/components/icon/readme.md
  packages/beeq/src/components/input/_storybook/bq-input.stories.tsx
  packages/beeq/src/global/scripts/global.ts
  packages/beeq/stencil.config.ts
Labels: feature 🛠

#1066 fix(Date picker): missing value accessor and model config
  packages/beeq/src/tools/angular-value-accessor-config.ts
  packages/beeq/src/tools/vue-model-config.ts
Labels: bug 🐛

#1070 chore(deps): update development dependencies
  package-lock.json
  package.json
  packages/beeq/src/components/alert/_storybook/bq-alert.stories.tsx
  packages/beeq/src/components/side-menu/_storybook/bq-side-menu.stories.tsx
Labels: chore ⚙️, dependencies 📦

#1072 chore(deps): update Angular to v18.x (major)
  package-lock.json
  package.json
Labels: chore ⚙️, dependencies 📦

#1075 fix(Slider): range thumbs being stuck when min/max values overlap
  packages/beeq/src/components/slider/bq-slider.tsx
Labels: bug 🐛

#1077 fix(Beeq Core): vite fails to resolve `@beeq/core/dist/*` paths
  packages/beeq-angular/package.json
  packages/beeq-react/package.json
  packages/beeq-tailwindcss/package.json
  packages/beeq-vue/package.json
  packages/beeq/README.md
  packages/beeq/package.json
Labels: bug 🐛

#1078 fix(Slider): lower value not updated when is equal to upper value
  packages/beeq/src/components/slider/bq-slider.tsx
  packages/beeq/src/shared/utils/__tests__/clamp.spec.ts
  packages/beeq/src/shared/utils/clamp.ts
  packages/beeq/src/shared/utils/index.ts
Labels: bug 🐛

#1079 chore(deps): update cally to v0.6.1
  package-lock.json
  package.json
  packages/beeq-angular/package.json
  packages/beeq-react/package.json
  packages/beeq-vue/package.json
  packages/beeq/.eslintrc.json
  packages/beeq/package.json
Labels: chore ⚙️, dependencies 📦
