Repository Endava/BEEQ, pull requests merged in 2024-06, with the labels that each got.

#1086 fix(Input): typo in CSS variables for padding start/end
  packages/beeq/src/components/input/scss/bq-input.variables.scss
Labels: bug 🐛

#1074 fix(Date Picker): clear incomplete range selection
  package-lock.json
  packages/beeq/package.json
  packages/beeq/src/components.d.ts
  packages/beeq/src/components/date-picker/_storybook/bq-date-picker.stories.tsx
  packages/beeq/src/components/date-picker/bq-date-picker.tsx
  packages/beeq/src/components/date-picker/readme.md
  packages/beeq/src/global/scripts/global.ts
Labels: bug 🐛

#1095 chore(Tailwind CSS): add support for missing CSS logical properties
  .sonarcloud.properties
  packages/beeq-tailwindcss/src/index.ts
  packages/beeq-tailwindcss/src/plugins/color-mix.ts
  packages/beeq-tailwindcss/src/plugins/index.ts
  packages/beeq-tailwindcss/src/plugins/logical-properties.ts
  sonar-project.properties
Labels: chore ⚙️

#1107 chore(deps): update tailwindcss to v3.4.4
  .github/renovate.json5
  .gitignore
  package-lock.json
  package.json
Labels: chore ⚙️, dependencies 📦

#1108 chore(deps): update npm dependencies
  .github/renovate.json5
  package-lock.json
  package.json
Labels: chore ⚙️, dependencies 📦

#1110 feat(Drawer): deprecate `placement` and add `position` property
  packages/beeq/src/components.d.ts
  packages/beeq/src/components/drawer/_storybook/bq-drawer.stories.tsx
  packages/beeq/src/components/drawer/bq-drawer.tsx
  packages/beeq/src/components/drawer/bq-drawer.types.ts
  packages/beeq/src/components/drawer/readme.md
Labels: feature 🛠

#1125 chore(Icon): remove the useless `icon-set` file listing all the icons
  packages/beeq/project.json
  packages/beeq/src/components/icon/_storybook/bq-icon.stories.tsx
  packages/beeq/src/components/icon/helper/icons-set.ts
  packages/beeq/src/shared/utils/assetsPath.ts
  tools/src/executors/icons/executor.ts
  tools/src/executors/icons/helpers/create.ts
  tools/src/executors/icons/helpers/download.ts
  tools/src/executors/icons/helpers/extract.ts
  tools/src/executors/icons/helpers/index.ts
  tools/src/executors/icons/schema.d.ts
Labels: chore ⚙️

#1093 feat(Select): add support for custom tag display on multiple variant
  packages/beeq/src/components/select/_storybook/bq-select.stories.tsx
  packages/beeq/src/components/select/bq-select.tsx
  packages/beeq/src/components/select/scss/bq-select.scss
Labels: feature 🛠

#1127 chore(deps): update puppeteer to v22.12.0
  package-lock.json
  package.json
Labels: chore ⚙️, dependencies 📦
