Repository Endava/BEEQ, pull requests merged in 2024-08, with the labels that each got.

#1180 chore(tailwind): support for negative values for logical properties inset/margin
  packages/beeq-tailwindcss/src/plugins/logical-properties.ts
  packages/beeq/src/components/checkbox/bq-checkbox.tsx
  packages/beeq/src/components/dropdown/_storybook/bq-dropdown.stories.tsx
  packages/beeq/src/components/icon/_storybook/bq-icon.stories.tsx
  packages/beeq/src/components/status/bq-status.tsx
  packages/beeq/src/components/steps/bq-steps.tsx
Labels: chore ⚙️

#1183 feat(Icon): deprecate `weight` property
  .vscode/settings.json
  packages/beeq/src/components.d.ts
  packages/beeq/src/components/drawer/bq-drawer.tsx
  packages/beeq/src/components/drawer/bq-drawer.types.ts
  packages/beeq/src/components/icon/_storybook/bq-icon.stories.tsx
  packages/beeq/src/components/icon/bq-icon.tsx
  packages/beeq/src/components/icon/bq-icon.types.ts
  packages/beeq/src/components/icon/readme.md
  packages/beeq/src/components/icon/scss/bq-icon.scss
  packages/beeq/src/shared/utils/assetsPath.ts
Labels: feature 🛠

#1091 feat(Tab): add orientation support
  packages/beeq/src/components.d.ts
  packages/beeq/src/components/tab-group/_storybook/bq-tab-group.stories.tsx
  packages/beeq/src/components/tab-group/bq-tab-group.tsx
  packages/beeq/src/components/tab-group/readme.md
  packages/beeq/src/components/tab-group/scss/bq-tab-group.scss
  packages/beeq/src/components/tab/_storybook/bq-tab.stories.tsx
  packages/beeq/src/components/tab/bq-tab.tsx
  packages/beeq/src/components/tab/bq-tab.types.ts
  packages/beeq/src/components/tab/readme.md
  packages/beeq/src/components/tab/scss/bq-tab.scss
Labels: feature 🛠

#1211 feat(Input): enable support for form-associated
  packages/beeq/src/components/input/_storybook/bq-input.stories.tsx
  packages/beeq/src/components/input/bq-input.tsx
Labels: feature 🛠

#1212 feat(Select): enable support for form-associated
  packages/beeq/src/components/select/_storybook/bq-select.stories.tsx
  packages/beeq/src/components/select/bq-select.tsx
Labels: feature 🛠

#1214 chore(deps): update nx to v19.6.0
  .github/pull_request_template.md
  .github/renovate.json5
  package-lock.json
  package.json
  patches/@storybook+core+8.2.7.patch
Labels: chore ⚙️, dependencies 📦

#1213 feat(Checkbox): enable support for form-associated
  .github/renovate.json5
  packages/beeq/src/components.d.ts
  packages/beeq/src/components/checkbox/_storybook/bq-checkbox.stories.tsx
  packages/beeq/src/components/checkbox/bq-checkbox.tsx
  packages/beeq/src/components/checkbox/readme.md
Labels: feature 🛠

#1217 fix(Select): display value is not shown when initial value is set
  packages/beeq/src/components/select/bq-select.tsx
Labels: bug 🐛

#1218 fix(Assets): set SVG base path in the window object to keep persistence
  packages/beeq/src/shared/utils/assetsPath.ts
Labels: bug 🐛

#1230 fix(Alert): make close icon customizable via slot
  packages/beeq/src/components.d.ts
  packages/beeq/src/components/alert/_storybook/bq-alert.stories.tsx
  packages/beeq/src/components/alert/bq-alert.tsx
  packages/beeq/src/components/alert/readme.md
Labels: bug 🐛

#1236 refactor(Notification): set notification portal from the components lifecycle: `connectedCallback()`
  packages/beeq/src/components/notification/bq-notification.tsx
  packages/beeq/src/components/notification/readme.md
Labels: refactor 🧑🏼‍🔧

#1237 refactor(Toast): set toast portal from the components lifecycle: `connectedCallback()`
  packages/beeq/src/components/toast/__tests__/bq-toast.e2e.ts
  packages/beeq/src/components/toast/_storybook/bq-toast.stories.tsx
  packages/beeq/src/components/toast/bq-toast.tsx
  packages/beeq/src/components/toast/readme.md
Labels: refactor 🧑🏼‍🔧

#1238 refactor(Assets Path): set `bqSVGBasePath` when window and document objects are available
  packages/beeq/src/components/icon/_storybook/bq-icon.stories.tsx
  packages/beeq/src/shared/utils/assetsPath.ts
Labels: refactor 🧑🏼‍🔧
