Repository Endava/BEEQ, pull requests merged in 2024-01, with the labels that each got.

#741 fix(Accordion): skip focus if `disabled="true"`
  package-lock.json
  packages/beeq/src/components/accordion-group/bq-accordion-group.tsx
  packages/beeq/src/components/accordion-group/readme.md
  packages/beeq/src/components/accordion-group/scss/bq-accordion-group.scss
  packages/beeq/src/components/accordion/bq-accordion.tsx
Labels: bug 🐛

#742 feat(Icon): add support for custom source (`src`) and custom assets path
  package-lock.json
  package.json
  packages/beeq-tailwindcss/package.json
  packages/beeq/package.json
  packages/beeq/src/components.d.ts
  packages/beeq/src/components/icon/_storybook/bq-icon.stories.tsx
  packages/beeq/src/components/icon/bq-icon.tsx
  packages/beeq/src/components/icon/helper/request.ts
  packages/beeq/src/components/icon/readme.md
  packages/beeq/src/global/assets/wallet.svg
  packages/beeq/stencil.config.ts
Labels: feature 🛠

#755 docs(Storybook): enable visual tests addon
  chromatic.config.json
  package-lock.json
  package.json
  packages/beeq/.storybook/main.ts
Labels: documentation 📚

#757 chore(deps): update dependency nx-stylelint to v17.1.1
  .circleci/config.yml
  .github/renovate.json5
  package-lock.json
  package.json
  packages/beeq/stencil.config.ts
Labels: chore ⚙️, dependencies 📦

#767 fix(Dialog): prop `footerAppearance` typo and open/close animations improvement
  package-lock.json
  packages/beeq/package.json
  packages/beeq/src/components.d.ts
  packages/beeq/src/components/dialog/bq-dialog.tsx
  packages/beeq/src/components/dialog/readme.md
  packages/beeq/src/components/dialog/scss/bq-dialog.scss
  packages/beeq/src/shared/utils/props.ts
Labels: bug 🐛

#768 fix(Notification): improve open/close animations
  packages/beeq/src/components.d.ts
  packages/beeq/src/components/dialog/bq-dialog.tsx
  packages/beeq/src/components/dropdown/bq-dropdown.tsx
  packages/beeq/src/components/notification/_storybook/bq-notification.stories.tsx
  packages/beeq/src/components/notification/bq-notification.tsx
  packages/beeq/src/components/notification/readme.md
  packages/beeq/src/components/notification/scss/bq-notification.scss
  packages/beeq/src/components/panel/bq-panel.tsx
  packages/beeq/src/components/select/bq-select.tsx
Labels: bug 🐛

#769 fix(Alert): improve open/close animation
  packages/beeq/src/components.d.ts
  packages/beeq/src/components/alert/bq-alert.tsx
  packages/beeq/src/components/alert/scss/bq-alert.scss
Labels: bug 🐛

#787 docs(project): update README Running the project section
  README.md
Labels: documentation 📚

#788 docs(Accordion): add css variables description
  packages/beeq/src/components/accordion/scss/bq-accordion.variables.scss
Labels: documentation 📚
