Repository Endava/BEEQ, pull requests merged in 2024-02, with the labels that each got.

#800 test(Accordion): add e2e test
  packages/beeq/src/components/accordion/__tests__/bq-accordion.e2e.ts
Labels: test 🧪

#807 chore(deps): update NPM dependencies
  .github/renovate.json5
  package-lock.json
  package.json
Labels: chore ⚙️, dependencies 📦

#806 feat(Card): add new `bq-card` component
  packages/beeq/src/components.d.ts
  packages/beeq/src/components/card/__tests__/bq-card.e2e.ts
  packages/beeq/src/components/card/_storybook/bq-card.mdx
  packages/beeq/src/components/card/_storybook/bq-card.stories.tsx
  packages/beeq/src/components/card/bq-card.tsx
  packages/beeq/src/components/card/bq-card.types.ts
  packages/beeq/src/components/card/readme.md
  packages/beeq/src/components/card/scss/bq-card.scss
  packages/beeq/src/components/card/scss/bq-card.variables.scss
Labels: feature 🛠

#817 feat(Alert): add `border` property to facilitate dynamic border-radius changes
  packages/beeq/src/components.d.ts
  packages/beeq/src/components/alert/_storybook/bq-alert.stories.tsx
  packages/beeq/src/components/alert/bq-alert.tsx
  packages/beeq/src/components/alert/bq-alert.types.ts
  packages/beeq/src/components/alert/readme.md
Labels: feature 🛠

#818 feat(Dialog): add `border` property to facilitate dynamic border-radius changes
  packages/beeq/src/components.d.ts
  packages/beeq/src/components/dialog/_storybook/bq-dialog.stories.tsx
  packages/beeq/src/components/dialog/bq-dialog.tsx
  packages/beeq/src/components/dialog/bq-dialog.types.ts
  packages/beeq/src/components/dialog/readme.md
Labels: feature 🛠

#819 feat(Notification): add `border` property to facilitate dynamic border-radius changes
  packages/beeq/src/components.d.ts
  packages/beeq/src/components/notification/_storybook/bq-notification.stories.tsx
  packages/beeq/src/components/notification/bq-notification.tsx
  packages/beeq/src/components/notification/bq-notification.types.ts
  packages/beeq/src/components/notification/readme.md
Labels: feature 🛠

#821 chore(deps): use `@chromatic-com/storybook` for visual tests
  package-lock.json
  package.json
  packages/beeq/.storybook/main.ts
  packages/beeq/vite.config.ts
Labels: chore ⚙️

#828 test(Accordion): add e2e tests for accordion-group
  packages/beeq/src/components/accordion-group/__tests__/bq-accordion-group.e2e.ts
  packages/beeq/src/components/accordion-group/scss/bq-accordion-group.variables.scss
Labels: test 🧪

#829 docs: update missing scss variables description
  packages/beeq/src/components/checkbox/scss/bq-checkbox.variables.scss
  packages/beeq/src/components/divider/scss/bq-divider.variables.scss
  packages/beeq/src/components/icon/scss/bq-icon.variables.scss
  packages/beeq/src/components/option-group/scss/bq-option-group.scss
  packages/beeq/src/components/option-group/scss/bq-option-group.variables.scss
  packages/beeq/src/components/option/scss/bq-option.scss
  packages/beeq/src/components/option/scss/bq-option.variables.scss
  packages/beeq/src/components/panel/scss/bq-panel.scss
  packages/beeq/src/components/panel/scss/bq-panel.variables.scss
  packages/beeq/src/components/radio/scss/bq-radio.variables.scss
  packages/beeq/src/components/side-menu-item/scss/bq-side-menu-item.variables.scss
  packages/beeq/src/components/side-menu/scss/bq-side-menu.variables.scss
  packages/beeq/src/components/slider/scss/bq-slider.scss
  packages/beeq/src/components/slider/scss/bq-slider.variables.scss
  packages/beeq/src/components/spinner/scss/bq-spinner.scss
  packages/beeq/src/components/spinner/scss/bq-spinner.variables.scss
  packages/beeq/src/components/status/scss/bq-status.scss
  packages/beeq/src/components/status/scss/bq-status.variables.scss
  packages/beeq/src/components/switch/scss/bq-switch.scss
  packages/beeq/src/components/switch/scss/bq-switch.variables.scss
  packages/beeq/src/components/tab/scss/bq-tab.scss
  packages/beeq/src/components/tab/scss/bq-tab.variables.scss
  packages/beeq/src/components/tag/scss/bq-tag.variables.scss
Labels: documentation 📚, refactor 🧑🏼‍🔧

#863 chore: update packages scope from `@bee-q` to `@beeq`
  CHANGELOG.md
  package-lock.json
  packages/beeq-angular/.eslintrc.json
  packages/beeq-angular/README.md
  packages/beeq-angular/ng-package.json
  packages/beeq-angular/package.json
  packages/beeq-angular/src/beeq.module.ts
  packages/beeq-react/.eslintrc.json
  packages/beeq-react/README.md
  packages/beeq-react/jest.config.ts
  packages/beeq-react/package.json
  packages/beeq-tailwindcss/README.md
  packages/beeq-tailwindcss/package.json
  packages/beeq-vue/.eslintrc.json
  packages/beeq-vue/README.md
  packages/beeq-vue/package.json
  packages/beeq-vue/src/plugin.ts
  packages/beeq/.storybook/main.ts
  packages/beeq/.storybook/manager.ts
  packages/beeq/README.md
  packages/beeq/package.json
  packages/beeq/project.json
  packages/beeq/src/components/checkbox/_storybook/bq-checkbox.stories.tsx
  packages/beeq/src/components/icon/_storybook/bq-icon.mdx
  packages/beeq/src/components/icon/_storybook/bq-icon.stories.tsx
  packages/beeq/src/components/icon/helper/icons-set.ts
  packages/beeq/src/components/icon/scss/bq-icon.scss
  packages/beeq/src/components/radio-group/_storybook/bq-radio-group.stories.tsx
  packages/beeq/src/components/side-menu/scss/bq-side-menu.variables.scss
  packages/beeq/src/global/scripts/esm-loader.js
  packages/beeq/src/global/scripts/zeroheight-svg-loader.js
  packages/beeq/src/index.html
  packages/beeq/stencil.config.ts
  tools/src/executors/icons/helpers/create.ts
  tsconfig.base.json
Labels: chore ⚙️, dependencies 📦

#869 chore(Chromatic): set `storybookBaseDir` config option
  README.md
  chromatic.config.json
  package-lock.json
Labels: chore ⚙️
