Repository Endava/BEEQ, pull requests merged in 2024-03, with the labels that each got.

#893 fix(Theme): change Endava theme font family according to the new brand
  .circleci/config.yml
  packages/beeq-tailwindcss/src/theme/endava/root.ts
  packages/beeq/src/global/styles/fonts/_poppins.scss
  packages/beeq/src/global/styles/fonts/_roboto.scss
  packages/beeq/src/global/styles/fonts/index.scss
Labels: bug 🐛

#901 feat(accordion): add appearance and size to accordion group
  packages/beeq/src/components.d.ts
  packages/beeq/src/components/accordion-group/__tests__/bq-accordion-group.e2e.ts
  packages/beeq/src/components/accordion-group/_storybook/bq-accordion-group.stories.tsx
  packages/beeq/src/components/accordion-group/bq-accordion-group.tsx
  packages/beeq/src/components/accordion-group/readme.md
Labels: feature 🛠

#904 chore(GitHub): add bug, feature request and pull request templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/pull_request_template.md
  package-lock.json
  package.json
Labels: chore ⚙️

#913 perf(CSS): remove the massive wall of empty CSS properties added by Tailwind CSS
  .github/CODEOWNERS
  tailwind.config.ts
Labels: chore ⚙️

#917 chore(StyleLint): improve rules and `.scss` file association
  .stylelintrc.json
  .vscode/settings.json
  packages/beeq/.stylelintrc.json
  packages/beeq/src/components/switch/bq-switch.tsx
  packages/beeq/src/components/switch/scss/bq-switch.scss
  packages/beeq/src/components/switch/scss/bq-switch.variables.scss
  packages/beeq/src/global/styles/_components.scss
  packages/beeq/src/global/styles/default.scss
Labels: chore ⚙️

#921 fix(Vue): wrapped component's camelCase events not being listened to
  package-lock.json
  package.json
  packages/beeq-angular/project.json
  packages/beeq-react/project.json
  packages/beeq-vue/project.json
  packages/beeq-vue/src/plugin.ts
Labels: bug 🐛

#929 fix(Dialog): wrong position on entry/leave transition
  package-lock.json
  packages/beeq/package.json
  packages/beeq/src/components/alert/bq-alert.tsx
  packages/beeq/src/components/dialog/bq-dialog.tsx
  packages/beeq/src/components/dialog/scss/bq-dialog.scss
  packages/beeq/src/components/notification/bq-notification.tsx
  packages/beeq/src/components/notification/scss/bq-notification.scss
  packages/beeq/src/shared/utils/index.ts
  packages/beeq/src/shared/utils/transition.ts
  tailwind.config.ts
Labels: bug 🐛

#918 feat(Drawer): add new `bq-drawer` component
  packages/beeq/.storybook/preview.ts
  packages/beeq/src/components.d.ts
  packages/beeq/src/components/alert/scss/bq-alert.scss
  packages/beeq/src/components/button/readme.md
  packages/beeq/src/components/dialog/_storybook/bq-dialog.mdx
  packages/beeq/src/components/divider/readme.md
  packages/beeq/src/components/drawer/__tests__/bq-drawer.e2e.ts
  packages/beeq/src/components/drawer/_storybook/bq-drawer.mdx
  packages/beeq/src/components/drawer/_storybook/bq-drawer.stories.tsx
  packages/beeq/src/components/drawer/bq-drawer.tsx
  packages/beeq/src/components/drawer/bq-drawer.types.ts
  packages/beeq/src/components/drawer/readme.md
  packages/beeq/src/components/drawer/scss/bq-drawer.scss
  packages/beeq/src/components/drawer/scss/bq-drawer.variables.scss
  packages/beeq/src/components/icon/readme.md
Labels: feature 🛠

#951 fix(Accordion): improve open/close animations and handle `bqAfterOpen` and `bqAfterClose` events
  packages/beeq/src/components.d.ts
  packages/beeq/src/components/accordion-group/bq-accordion-group.tsx
  packages/beeq/src/components/accordion/__tests__/bq-accordion.e2e.ts
  packages/beeq/src/components/accordion/_storybook/bq-accordion.stories.tsx
  packages/beeq/src/components/accordion/bq-accordion.tsx
  packages/beeq/src/components/accordion/helper/index.ts
  packages/beeq/src/components/accordion/readme.md
  packages/beeq/src/components/accordion/scss/bq-accordion.scss
Labels: bug 🐛

#959 feat(Tooltip): allow the component to be always visible
  packages/beeq/src/components.d.ts
  packages/beeq/src/components/tooltip/_storybook/bq-tooltip.stories.tsx
  packages/beeq/src/components/tooltip/bq-tooltip.tsx
  packages/beeq/src/components/tooltip/readme.md
Labels: feature 🛠

#946 feat(Progress): add new `bq-progress` component
  packages/beeq/src/components.d.ts
  packages/beeq/src/components/progress/__tests__/bq-progress.e2e.ts
  packages/beeq/src/components/progress/_storybook/bq-progress.mdx
  packages/beeq/src/components/progress/_storybook/bq-progress.stories.tsx
  packages/beeq/src/components/progress/bq-progress.tsx
  packages/beeq/src/components/progress/bq-progress.types.ts
  packages/beeq/src/components/progress/readme.md
  packages/beeq/src/components/progress/scss/bq-progress.scss
  packages/beeq/src/components/progress/scss/bq-progress.variables.scss
  packages/beeq/src/components/tag/bq-tag.tsx
  packages/beeq/src/components/tooltip/bq-tooltip.tsx
  packages/beeq/src/components/tooltip/readme.md
  packages/beeq/src/components/tooltip/scss/bq-tooltip.scss
Labels: feature 🛠

#968 refactor(Icon): flatten icon SVG files when extracted and improve assets path
  packages/beeq/src/components/icon/bq-icon.tsx
  packages/beeq/src/index.ts
  packages/beeq/src/shared/utils/assetsPath.ts
  packages/beeq/src/shared/utils/index.ts
  tools/src/executors/icons/helpers/extract.ts
Labels: refactor 🧑🏼‍🔧
